### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by aaronraimist** [dcu/1p#1]
I am getting a runtime error after entering my password, seems like its not able to find the 1Password keychain. I appear to have my keychain in the right location `$HOME/Dropbox/1Password/1Password.agilekeychain`.

OS: Fedora 21

https://github.com/dcu/1p/blob/master/cli/find_keychain.go#L33

```
[aaronraimist@saturn 1p]$ 1p q google
```

```
Enter your password: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x450b80]

goroutine 1 [running]:
github.com/dcu/1p/cli.FindAllVaultPaths(0x0, 0x0, 0x0)
    /home/aaronraimist/go/src/github.com/dcu/1p/cli/find_keychain.go:36 +0x180
github.com/dcu/1p/cli.FindVaultsForPassword(0xc208030940, 0x4, 0x0, 0x0, 0x0)
    /home/aaronraimist/go/src/github.com/dcu/1p/cli/find_keychain.go:12 +0x4b
main.main()
    /home/aaronraimist/go/src/github.com/dcu/1p/1p.go:22 +0x112
```

**Comment by dcu** [comment]
@aaronraimist Thanks for reporting this.

Apparently the current user can't be resolved. Please try updating to the last version to see what's the new error:

```
go get -u github.com/dcu/1p
```

**Comment by dcu** [comment]
looks like it's related to this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1135152

**Comment by dcu** [comment]
@aaronraimist I just pushed a new commit, it should fix this issue. Please try it and let me know how it goes.

**Comment by aaronraimist** [comment]
Just tested, it is working now thanks!

You may also want to add 'xclip' to the dependencies in the README or produce an error asking you to install 'xclip' if command not found. It's already pretty much there but a nicer error might be better for the end user.
`panic: exec: "xclip": executable file not found in $PATH`
